### ISSUE TITLE
Server returns 500 once adding a new hobby

### ISSUE THREAD

**Issue by eekallio** [City-of-Helsinki/harrastuspassi-ui-web#26]
-Log in as a non-superuser account
-Create a new hobby
-Save the hobby
-Rerouted to the front page with error 500

**Comment by eekallio** [comment]
Currently only reproduced in a production environment.

**Comment by indigane** [comment]
Error happens in `/hobbies/` Hobby object list API endpoint.

`KeyError` from this line
https://github.com/django-guardian/django-guardian/blob/v2.1.0/guardian/core.py#L264

The key itself looks ok, but it does not exist for some reason. Needs debugging in the env where it can be reproduced.
